/*
NOTA:
YA QUE SE HICIERON MUCHAS PAGINAS, Y ESO PODRIA OBLIGAR AL USUARIO A ESTAR SALTANDO ENTRE PAGINAS, CREO QUE QUEDA MEJOR LO SIGUIENTE

USAR SOLAMENTE ESTA PAGINA, PEROOOOO YA QUE TENGO FUNCIONANDO BONITO LOS TABS Y EL ACORDEON, AQUI VA LA IDEA

UNA PAGINA QUE TENGA 3 TABS PRINCIPALES, Y DENTRO DE CADA UNO EL ACORDEON PARA LOS SUBELMENTOS. 
DE ESTA MANERA EL COMPONENTE PADRE VA A TENER EL CONTROL DEL OBJETO QUE ENCIERRA A TODO LOS SUB MODELOS.

SELECCIONAR EL TIPO DE CENTRAL

- COSTOS OPERATIVOS
    - COSTOS DE MANTENIMIENTO
    - COSTOS DE PRODUCCION
- STAFF/PERSONAL
    - PARAFISCALES
    - QUIMICO FARMACEUTICO
    - AUXILIAR DE FARMACIA
- MATERIALES
    - EQUIPO DE TRABAJO ESTERIL
    - HIGIENE Y LIMPIEZA
    - PROTECION PERSONAL
- OTROS
    - EQUIPOS AUTOMATIZADOS

NOTA: HAY QUE ELIMINAR LAS PAGINAS QUE NO SE VAN A USAR

USAR COMO REFERENCIA "RawMaterialsDetails"

*/

const OperatingCostsSettingsPage = () => {
    return (
        <div>
            <div className="bg-white border rounded-xl shadow-md p-6 mb-6">
                CONTENT HERE
            </div>
        </div>
    );
}

export default OperatingCostsSettingsPage;